### ISSUE TITLE
Make CSR v2

### ISSUE THREAD

**Issue by el22or** [Develomon/csr#10]
Make CSR v2, with super function which returns object full of all information about sprite and image.
- Image width
- Image height
- Sprite width
- Sprite height
- Sprite URL
- Background position
  - Horizontal
  - Vertical
- Background size
  - Width
  - Height
- ...

All this info in one Sass object...

**Comment by el22or** [comment]
Also implement solution to _position_ (align) images left/right in vertical, and top/bottom in horizontal sprite layout.

**Comment by el22or** [comment]
Implement solution to support custom positioning for X or Y.

``` css
.selector {
  background-position: left -607px bottom 10px;
}
```
